yatube/about/urls.py
from django.urls import path
from . import views


app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    # path('index_search/', views.index_search, name='index_search'),
    path('group/<slug:slug>/', views.group_posts, name='group_list'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('create/', views.post_create, name='post_create'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
    path(
        'posts/<int:post_id>/comment/',
        views.add_comment,
        name='add_comment'),
    path('follow/', views.follow_index, name='follow_index'),
    path(
        'profile/<str:username>/follow/',
        views.profile_follow,
        name='profile_follow'
    ),
    path(
        'profile/<str:username>/unfollow/',
        views.profile_unfollow,
        name='profile_unfollow'
    ),
]

yatube/yatube/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static

urlpatterns = [
    path('', include('posts.urls')),
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls', namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
]

handler404 = 'core.views.page_not_found'
handler403 = 'core.views.csrf_failure'

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT,
    )
    import debug_toolbar
    urlpatterns += path('__debug__/', include(debug_toolbar.urls)),

yatube/templates/includes/footer.html
{% load tz %}
{% get_current_timezone as TIME_ZONE %}
<p>
  {% timezone TIME_ZONE %}
    {% now "Y" %}
  {% endtimezone %}
  <span style="color:red">Скандинавские</span> мифы и легенды
</p>

yatube/templates/includes/header.html
{% load static %}
<style>
  body {
    background-image: url("{% static 'img/фон.jpg' %}");
    background-repeat: no-repeat;
    background-size: cover;
    background-position: center center;
  }
  .text-center:hover .hover-panel {
    display: block;
    position: fixed;
    top: 50%;
    left: 50%;
    transform: translate(-50%, -50%);
  }
  
  .hover-panel {
    display: none;
    position: fixed;
    top: 100%;
    left: 0;
    background-color: #fff;
    width: 50%;
    padding: 1rem;
    box-shadow: 0px 4px 8px rgba(0, 0, 0, 0.1);
  }

  .hover-panel a {
    color: #fff;
    background-color: #007bff;
    padding: 0.5rem 1rem;
    border-radius: 0.5rem;
    text-decoration: none;
    display: inline-block;
    margin-top: 1rem;
  }
  
  .hover-panel p {
    margin: 0;
  } 
</style>
<nav class="navbar navbar-light" style="background-color: #41a0a7">
    <div class="container">
      {% load static %}
        <a class="navbar-brand" href="{% url 'posts:index' %}">
          <img src="{% static 'img/Yggdrasil.png' %}" 
            width="30" 
            height="30" 
            class="d-inline-block align-top" 
            alt="">
          <span style="color:red">Мифы</span> и легенды
        </a>
      {% with request.resolver_match.view_name as view_name %}
      <ul class="nav nav-pills">
        <li class="nav-item"> 
          <a class="nav-link nav-link link-light
            {% if view_name  == 'about:author' %} 
              active
            {% endif %}"
            href="{% url 'about:author' %}">Об авторе</a>
        </li>
        <li class="nav-item">
          <a class="nav-link nav-link link-light 
            {% if view_name  == 'about:tech' %} 
              active
            {% endif %}"
            href="{% url 'about:tech' %}">Технологии</a>
        </li>
        {% if user.is_authenticated %}
        <li class="nav-item"> 
          <a class="nav-link link-light
            {% if view_name  == 'posts:post_create' %} 
              active
            {% endif %}"
            href="{% url 'posts:post_create' %}">Новая запись</a>
        </li>
        <li class="nav-item"> 
          <a class="nav-link link-light
            {% if view_name  == 'users:password_reset_form' %} 
              active
            {% endif %}" 
            href="{% url 'users:password_reset_form' %}">Изменить пароль</a>
        </li>
        <li class="nav-item">
          <a class="nav-link nav-link link-light
            {% if view_name  == 'users:logout' %} 
              active
            {% endif %}" 
            href="{% url 'users:logout' %}">Выйти</a>
        </li>
        <li class="nav-link link-dark">
          Пользователь: {{ user.username }}
          {% csrf_token %}
        </li>
        {% else %}
        <li class="nav-item"> 
        <a class="nav-link link-light{% if view_name  == 'users:login' %} 
          active
        {% endif %}"
        href="{% url 'users:login' %}">Войти</a>
        </li>
        <li class="nav-item"> 
          <a class="nav-link link-light
          {% if view_name  == 'users:signup' %} 
            active
          {% endif %}" 
          href="{% url 'users:signup' %}">Регистрация</a>
        </li>
        {% endif %}
      {% endwith %} 
      </ul>
    </div>
  </nav>      

yatube/templates/includes/paginator.html
{% if page_obj.has_other_pages %}
  <nav aria-label="Page navigation" class="my-5">
    <ul class="pagination">
      {% if page_obj.has_previous %}
        <li class="page-item">
          <a class="page-link" href="?page=1">Первая</a></li>
        <li class="page-item">
          <a class="page-link"
             href="?page={{ page_obj.previous_page_number|addslashes }}{{ page_obj.url_with_params }}">
            Предыдущая
          </a>
        </li>
      {% endif %}
      {% for i in page_obj.paginator.page_range %}
        {% if page_obj.number == i %}
          <li class="page-item active">
            <span class="page-link">{{ i }}</span>
          </li>
        {% else %}
          <li class="page-item">
            <a class="page-link" href="?page={{ i }}">{{ i }}</a>
          </li>
        {% endif %}
      {% endfor %}
      {% if page_obj.has_next %}
        <li class="page-item">
          <a class="page-link"
             href="?page={{ page_obj.next_page_number }}">
            Следующая
          </a>
        </li>
        <li class="page-item">
          <a class="page-link"
             href="?page={{ page_obj.paginator.num_pages }}">
            Последняя
          </a>
        </li>
      {% endif %}
    </ul>
  </nav>
{% endif %}

yatube/templates/includes/sort_paginator.html
{% if page_obj.has_other_pages %}
  <nav class="paginator">
    <ul class="pagination">
      {% if page_obj.has_previous %}
        <li class="page-item">
          <a class="page-link" href="?page=1&sort={{ sort }}&direction={{ direction }}">Первая</a>
        </li>
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.previous_page_number }}&sort={{ sort }}&direction={{ direction }}">Предыдущая</a>
        </li>
      {% endif %}
      {% for i in page_obj.paginator.page_range %}
        {% if page_obj.number == i %}
          <li class="page-item active">
            <span class="page-link">{{ i }}</span>
          </li>
        {% else %}
          <li class="page-item">
            <a class="page-link" href="?page={{ i }}&sort={{ sort }}&direction={{ direction }}">{{ i }}</a>
          </li>
        {% endif %}
      {% endfor %}
      {% if page_obj.has_next %}
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.next_page_number }}&sort={{ sort }}&direction={{ direction }}">Следующая</a>
        </li>
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}&sort={{ sort }}&direction={{ direction }}">Последняя</a>
        </li>
      {% endif %}
    </ul>
  </nav>
{% endif %}

yatube/templates/includes/style.html
{% load static %}
<style>
body {
    background-image: url("{% static 'img/фон.jpg' %}");
    background-repeat: no-repeat;
    background-size: cover;
    background-position: center center;

  }
  html, body {
    height: 100%;
  }

  .post-section {
    background-color: rgba(0,0,0,0.5);
    padding: 15px;
    color: #fff;
  }
  .modal {
    position: fixed;
    top: 75%;
    left: 50%;
    transform: translate(-50%, -50%);
  }
  a {
    color: #00fffa;
    text-decoration: none;
    background-color: transparent
}
    .list-group-item {
        background-color: rgba(0,0,0,0.3);
        align-items: center;
        color: #fff;
        width: 100%;
    }

    .modal-content {
        background-color: rgba(0,0,0,0.7);
        padding: 15px;
        color: #fff;
    }
    
    .list-group-item a {
      color: #fff;
      text-decoration: none;
    }
    
    .list-group-item:hover {
      background-color: rgba(0, 0, 0, 0.03);
    }
    
    .list-group-item.active {
      background-color: rgba(0, 0, 0, 0.05);
    }

    .scrollable-cell {
      overflow: auto;
      max-height: 200px;
    }

    .scrollable-cell::-webkit-scrollbar {
      width: 10px;
    }
    
    .scrollable-cell::-webkit-scrollbar-thumb {
      background: #ccc;
      border-radius: 5px;
    }
    
    .scrollable-cell::-webkit-scrollbar-track {
      background: #f2f2f2;
    }

    .active {
      background-color: #4CAF50;
      color: white;
    }

    #postImageContainer {
      height: 400px;
      overflow: auto;
      padding-left: 12px;
      padding-right: 12px;
    }
    
    #postImage {
      object-fit: contain;
      width: 100%;
      height: 100%;
    }

</style>

yatube/templates/includes/switcher.html
{% if user.is_authenticated %}
    <div class="row my-3">
        <ul class="nav nav-tabs">
            <li class="nav-item">
                <a style="color: #212529; vertical-align: bottom"
                    class="nav-link link-light"
                    href="?sort=pub_date&direction={% if direction == 'desc' %}asc{% else %}desc{% endif %}">
                    ⇅
                    {% if sort == 'pub_date' %}
                    {% if direction == 'desc' %} &#9660; {% else %} &#9650; {% endif %}
                    {% endif %}
                </a>
            </li>
            {% comment %} <li class="nav-item">
                <a
                class="nav-link link-light"
                href="{% url 'posts:index' %}">
                Все авторы
                </a>
            </li>
            <li class="nav-item">
                <a
                class="nav-link link-light"
                href="{% url 'posts:follow_index' %}">
                Избранные авторы
                </a>
            </li> {% endcomment %}
        </ul>
    </div>
{% endif %}